# Generated by Django 4.2 on 2023-06-03 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=150)),
                ('harga', models.FloatField()),
                ('harga_diskon', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=150)),
                ('deskripsi', models.TextField()),
                ('gambar_category', models.ImageField(upload_to='product_pics')),
                ('label', models.CharField(choices=[('NEW', 'primary'), ('SALE', 'info'), ('BEST', 'danger')], max_length=4)),
                ('kategori', models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='produkitem',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='toko.category'),
        ),
    ]
