# Generated by Django 4.2 on 2023-06-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0009_category_produkitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='category',
            name='harga_diskon',
        ),
    ]
