# Generated by Django 4.2 on 2023-06-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0010_remove_category_harga_remove_category_harga_diskon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='category',
            name='label',
        ),
    ]
