# Generated by Django 4.2 on 2023-06-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0011_remove_category_kategori_remove_category_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nama_produk',
            new_name='nama_kategori',
        ),
    ]
