# Generated by Django 4.2 on 2023-06-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0012_rename_nama_produk_category_nama_kategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nama_kategori',
            new_name='nama_produk',
        ),
    ]
