# Generated by Django 4.2 on 2023-06-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0020_produkitem_spesifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='gambar_1',
            field=models.ImageField(default=False, upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='gambar_2',
            field=models.ImageField(default=False, upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='produkitem',
            name='gambar_3',
            field=models.ImageField(default=False, upload_to='product_pics'),
        ),
    ]
