# Generated by Django 4.2 on 2023-06-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0021_produkitem_gambar_1_produkitem_gambar_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkitem',
            name='rated',
            field=models.CharField(choices=[('1', 'satu'), ('2', 'dua'), ('3', 'tiga'), ('4', 'empat'), ('5', 'lima')], default=False, max_length=10),
        ),
    ]
