# Generated by Django 4.2 on 2023-06-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0022_produkitem_rated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nama_produk',
            new_name='nama_kategori',
        ),
    ]
